### ISSUE TITLE
How to generate a more dense grids3.npy file?

### ISSUE THREAD

**Issue by hnuzhy** [yd-yin/RotationLaplace#2]
Hi, thanks for your excellent work. Rencently, I'm using the Rotation Laplace to do 3D pose estimation tasks. And I have tried some methods to transfer you released file `grids3.npy` with 36864 3x3 rot_mats into a more sparse one (e.g., by calculating the geodesic distance between any mat and the unit mat `[[1,0,0], [0,1,0], [0,0,1]]` and then downsampling). But how can I change it into a more dense one with more than 36864 mats? Hoping for your reply!

**Comment by yd-yin** [comment]
Hi, thanks for your interest.

Please see if it helps: https://github.com/yd-yin/RotationLaplace?tab=readme-ov-file#equivolumetric-distretization-of-so3

**Comment by hnuzhy** [comment]
> Hi, thanks for your interest.
> 
> Please see if it helps: https://github.com/yd-yin/RotationLaplace?tab=readme-ov-file#equivolumetric-distretization-of-so3

OK. Thanks a lot for your reply~
